version: 2

requirements:
  signed_off_by:
    required: false

always_pending:
  title_regex: 'WIP'
  labels:
    - "Status: Work in Progress"

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(A|a)pproved|\+1'
  reset_on_push:
    enabled: true

groups:
  Developers:
    required: 2

    teams:
      - plugin-devs
    conditions:
      branches:
        - master
        - 1.0.0-bug-fixes
      files:
        include:
          - '*.php'
      labels:
        - 'PR: Bug Fixes'

    approve_by_comment:
      enabled: true

    author_approval:
      required: false

    reset_on_reopened:
      enabled: true

    reject_value: -1

  Rescuers:
    required: 2
    teams:
      - rescuers
    conditions:
      labels:
        exclude:
          - 'PR: Cosmetic'
    reset_on_push:
      enabled: true
    reset_on_reopened:
      enabled: true
    author_approval:
      ignored: false
    reject_value: -2
