name: PureEntitiesX
main: revivalpmmp\pureentities\PureEntities
version: 0.1.2_dev
api: [3.0.0-ALPHA3]

load: STARTUP
authors: ["milk0417", "RevivalPMMP"]
description: Implement all MCPE entities into your worlds
website: https://github.com/RevivalPMMP/PureEntitiesX

commands:
  pesummon:
    description: Summons a creature
    usage: "/pesummon <mob-name> <optional:playername>"
    permission: pureentities.command.pesummon

permissions:
 pureentities:
  default: op
  description: "Allows using all the PureEntities commands"
  children:
    pureentities.command:
    default: op
    description: "Allows using all the PureEntities commands"
    children:
      pureentities.command.pesummon:
      default: op
      description: "Allows spawning mobs"
