name: PureEntitiesX
main: revivalpmmp\pureentities\PureEntities
version: 0.1.2_dev
api: [2.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2]

load: STARTUP
authors: ["milk0417", "RevivalPMMP"]
description: Implement all MCPE entities into your worlds
website: https://github.com/RevivalPMMP/PureEntitiesX

commands:
  summon:
    description: Summons a creature
    usage: "/summon <mob-name> <optional:playername>"
    permission: pureentities.command.summon

permissions:
 pureentities:
  default: op
  description: "Allows using all the PureEntities commands"
  children:
    pureentities.command:
    default: op
    description: "Allows using all the PureEntities commands"
    children:
      pureentities.command.summon:
      default: op
      description: "Allows spawning mobs"
