# Default Config File for PureEntitiesX
---
# when set to true the creeper will explode and also destroy blocks
creeper:
  block-breaking-explosion: false

# control logfile logging
# possible: debug, warn, info
logfile:
  loglevel: info
...