# Default Config File for PureEntitiesX
---
# when set to true the creeper will explode and also destroy blocks
creeper:
  block-breaking-explosion: false

# control logfile logging
# possible: info = 0, warn = 1, debug = 2
logfile:
  loglevel: 0
...