# Default Config File for PureEntitiesX
creeper:
  block-breaking-explosion: false # when set to true the creeper will explode and also burst blocks

# control logfile logging
logfile:
  loglevel: info # possible: debug, info, warn